---
- hosts: virtuales
  serial: 1
  become: True
  gather_facts: false

  tasks:


  - name: actualizar distro
    yum: name=* state=latest update_cache=yes
    async: 7200
    poll: 30

  - name: Check for reboot hint.
    shell: if [ `rpm -qa --last|grep -e kernel-2.6 -e kernel-3 | cut -d'-' -f2- | awk '{print $1}' | head -n 1` != `uname -r` ]; then echo "reboot"; else echo "no"; fi
    register: reboot_hint
#    always_run: yes

  - name: Rebooting ...
    shell: sleep 2 && shutdown -r now "Yum kernel update applied"
    when: reboot_hint.stdout.find('reboot') != -1 
    async: 1
    poll: 0
    ignore_errors: true


  - name: wait a bit.
    pause: seconds=60
    when: reboot_hint.stdout.find('reboot') != -1


  - name: waiting for server to come back
    local_action: wait_for host={{ inventory_hostname }} state=started delay=10 port=22
    when: reboot_hint.stdout.find('reboot') != -1
  

